### ISSUE TITLE
Improve formatting for <script> and <label>

### ISSUE THREAD

**Issue by domaine-preston-roberts** [Shopify/prettier-plugin-liquid#217]
**Is your feature request related to a problem? Please describe.**
1. `<script>` is being formatted regardless of `printWidth` value
2. `<label>` could be improved when formatted based on `printWidth`

![image](https://github.com/Shopify/prettier-plugin-liquid/assets/113131178/44e8676c-1e31-45f6-b011-a9a8315d7dbd)

In the screenshot:
- the script tag is wrapped regardless of `printWidth`. It looks like that at 200 and 50.
- the angle bracket for the opening label tags are wrapped to the next line; see lines 7, 8, 13, 14, 17, and 18

**Describe the solution you'd like**
I think the formatting can be improved. Here are a few ideas:

![image](https://github.com/Shopify/prettier-plugin-liquid/assets/113131178/90e5c186-4e87-48b2-9f7c-adc41bf61301)

`<script>` tag should respect the `printWidth` value and `<label>` could do better at wrapping the last bracket, like the `<div>` is already doing.

**Checklist** 
- [x] I have checked and made sure that the proposal adheres to this plugin's [principles](https://github.com/Shopify/prettier-plugin-liquid/blob/main/docs/principles/index.md)

**Additional context**
I have disabled all other formatting extensions: ESLint, Prettier, and Stylelint

**Comment by charlespwd** [comment]
What you're seeing is explained in [these docs on whitespace handling](https://github.com/Shopify/theme-tools/blob/main/docs/prettier-plugin-liquid/whitespace-handling.md).

The official HTML plugin offered by prettier does the same thing. The **TL;DR** is that the lack of whitespace in HTML can be _meaningful_ and that the prettier plugin _should not_ alter the semantic meaning of source files by default. So we're forced to _maintain_ the lack of whitespace after formatting. `<label>...</label>` didn't have whitespace after `l>` nor before `</`, so the formatted code shouldn't have some. 

You can turn that off by setting [`--htmlWhitespaceSensitivity`](https://prettier.io/docs/en/options.html#html-whitespace-sensitivity) to `ignore`, but it would be dangerous to run it blindly on multiple files because you may end up with spacing in places you don't expect after running it. Your site might be broken in subtle ways. 

There's also [this article](https://prettier.io/blog/2018/11/07/1.15.0#whitespace-sensitive-formatting) which does a good job of explaining the same issue. 

---

Re the script tag, if there wasn't a new line and the print width is enough for the tag and closing tag to fit on a line, it doesn't break automatically for me. Are you sure that's true?

**Comment by domaine-preston-roberts** [comment]
Ok, understood about the label tag. I don't like it, but I understand.

I checked the script tag in a different repo that has similar formatting and linting settings and the issue isn't happening there. So I guess it's related to that one project.

**Comment by charlespwd** [comment]
> Ok, understood about the label tag. I don't like it, but I understand.

Like I said, you can set the following in your `.prettierrc` and have it format like you want. Just beware that if you run prettier wholesale, that might create bugs!
```json
{
  "htmlWhitespaceSensitivity": "ignore"
}
```

You can also enable that from the command line with the `--html-whitespace-sensitivity=ignore` flag.
